export { default as Navbar } from "./Navbar";
export { default as AddPatient } from "./AddPatient";
export { default as AddMedicine } from "./AddMedicine";
export { default as AddNewMedicine } from "./AddNewMedicine";
export { default as AddDiagnostics } from "./AddDiagnostics";
export { default as ViewAllPatients } from "./ViewAllPatients";
export { default as UpdatePatient } from "./UpdatePatient";
export { default as BillPatient } from "./BillPatient";
export { default as AddNewTest } from "./AddNewTest";
